services:
  snappy-nano:
    build:
      context: .
      dockerfile: Dockerfile
    image: snappy-nano:local-arm64
    container_name: snappy-nano
    volumes:
      - .:/ros2_ws
    privileged: true
    stdin_open: true
    tty: true
    command: /bin/bash