controller:
  ros__parameters:
    target_position: [0.0, 10.0, 0.0]
    target_roll: 0.0
    target_pitch: 0.0
    target_yaw: 0.0
    
    pid_x: [0.5, 0.0, 0.1]
    pid_y: [0.5, 0.0, 0.1]
    pid_z: [3.0, 1.0, 1.0]
    pid_roll: [0.5, 0.0, 0.1]
    pid_pitch: [0.5, 0.0, 0.1]
    pid_yaw: [0.15, 0.0, 5.0]