name: C/C++ CI

on:
  push:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up ROS 2 Humble
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Build with colcon
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --event-handlers console_cohesion+ --packages-select snappy_cpp
